export const CART_ITEM_INITIAL_STATE = "CART_ITEM_INITIAL_STATE";

export const CREATE_CART_ITEM = "CREATE_CART_ITEM";
export const CREATE_CART_ITEM_LOADING = "CREATE_CART_ITEM_LOADING";
export const CREATE_CART_ITEM_ERROR = "CREATE_CART_ITEM_ERROR";
export const CREATE_CART_ITEM_SUCCESS = "CREATE_CART_ITEM_SUCCESS";
export const CREATE_CART_ITEM_INITIAL_STATE = "CREATE_CART_ITEM_INITIAL_STATE";

export const LIST_CART_ITEM = "LIST_CART_ITEM";
export const LIST_CART_ITEM_LOADING = "LIST_CART_ITEM_LOADING";
export const LIST_CART_ITEM_ERROR = "LIST_CART_ITEM_ERROR";
export const LIST_CART_ITEM_SUCCESS = "LIST_CART_ITEM_SUCCESS";
export const LIST_CART_ITEM_INITIAL_STATE = "LIST_CART_ITEM_INITIAL_STATE";

export const GET_CART_ITEM = "GET_CART_ITEM";
export const GET_CART_ITEM_LOADING = "GET_CART_ITEM_LOADING";
export const GET_CART_ITEM_ERROR = "GET_CART_ITEM_ERROR";
export const GET_CART_ITEM_SUCCESS = "GET_CART_ITEM_SUCCESS";
export const GET_CART_ITEM_INITIAL_STATE = "GET_CART_ITEM_INITIAL_STATE";

export const EDIT_CART_ITEM_DATA = "EDIT_CART_ITEM_DATA";
export const EDIT_CART_ITEM = "EDIT_CART_ITEM";
export const EDIT_CART_ITEM_LOADING = "EDIT_CART_ITEM_LOADING";
export const EDIT_CART_ITEM_ERROR = "EDIT_CART_ITEM_ERROR";
export const EDIT_CART_ITEM_SUCCESS = "EDIT_CART_ITEM_SUCCESS";
export const EDIT_CART_ITEM_INITIAL_STATE = "EDIT_CART_ITEM_INITIAL_STATE";

export const DELETE_CART_ITEM_DATA = "DELETE_CART_ITEM_DATA";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const DELETE_CART_ITEM_LOADING = "DELETE_CART_ITEM_LOADING";
export const DELETE_CART_ITEM_ERROR = "DELETE_CART_ITEM_ERROR";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_INITIAL_STATE = "DELETE_CART_ITEM_INITIAL_STATE";



