export const FILE_INITIAL_STATE = "FILE_INITIAL_STATE";

export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_PROGRESS = "UPLOAD_FILE_PROGRESS";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";
export const UPLOAD_FILE_INITIAL_STATE = "UPLOAD_FILE_INITIAL_STATE";

export const DOWNLOAD_FILE = "DOWNLOAD_FILE";
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_ERROR = "DOWNLOAD_FILE_ERROR";
export const DOWNLOAD_FILE_INITIAL_STATE = "DOWNLOAD_FILE_INITIAL_STATE";

export const DELETE_FILE = "DELETE_FILE";
export const DELETE_FILE_LOADING = "DELETE_FILE_LOADING";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_ERROR = "DELETE_FILE_ERROR";
export const DELETE_FILE_INITIAL_STATE = "DELETE_FILE_INITIAL_STATE";