export const FOOD_CATEGORY_INITIAL_STATE = "FOOD_CATEGORY_INITIAL_STATE";

export const CREATE_FOOD_CATEGORY = "CREATE_FOOD_CATEGORY";
export const CREATE_FOOD_CATEGORY_LOADING = "CREATE_FOOD_CATEGORY_LOADING";
export const CREATE_FOOD_CATEGORY_ERROR = "CREATE_FOOD_CATEGORY_ERROR";
export const CREATE_FOOD_CATEGORY_SUCCESS = "CREATE_FOOD_CATEGORY_SUCCESS";
export const CREATE_FOOD_CATEGORY_INITIAL_STATE = "CREATE_FOOD_CATEGORY_INITIAL_STATE";

export const LIST_FOOD_CATEGORY = "LIST_FOOD_CATEGORY";
export const LIST_FOOD_CATEGORY_LOADING = "LIST_FOOD_CATEGORY_LOADING";
export const LIST_FOOD_CATEGORY_ERROR = "LIST_FOOD_CATEGORY_ERROR";
export const LIST_FOOD_CATEGORY_SUCCESS = "LIST_FOOD_CATEGORY_SUCCESS";
export const LIST_FOOD_CATEGORY_INITIAL_STATE = "LIST_FOOD_CATEGORY_INITIAL_STATE";

export const GET_FOOD_CATEGORY = "GET_FOOD_CATEGORY";
export const GET_FOOD_CATEGORY_LOADING = "GET_FOOD_CATEGORY_LOADING";
export const GET_FOOD_CATEGORY_ERROR = "GET_FOOD_CATEGORY_ERROR";
export const GET_FOOD_CATEGORY_SUCCESS = "GET_FOOD_CATEGORY_SUCCESS";
export const GET_FOOD_CATEGORY_INITIAL_STATE = "GET_FOOD_CATEGORY_INITIAL_STATE";

export const EDIT_FOOD_CATEGORY_DATA = "EDIT_FOOD_CATEGORY_DATA";
export const EDIT_FOOD_CATEGORY = "EDIT_FOOD_CATEGORY";
export const EDIT_FOOD_CATEGORY_LOADING = "EDIT_FOOD_CATEGORY_LOADING";
export const EDIT_FOOD_CATEGORY_ERROR = "EDIT_FOOD_CATEGORY_ERROR";
export const EDIT_FOOD_CATEGORY_SUCCESS = "EDIT_FOOD_CATEGORY_SUCCESS";
export const EDIT_FOOD_CATEGORY_INITIAL_STATE = "EDIT_FOOD_CATEGORY_INITIAL_STATE";

export const DELETE_FOOD_CATEGORY_DATA = "DELETE_FOOD_CATEGORY_DATA";
export const DELETE_FOOD_CATEGORY = "DELETE_FOOD_CATEGORY";
export const DELETE_FOOD_CATEGORY_LOADING = "DELETE_FOOD_CATEGORY_LOADING";
export const DELETE_FOOD_CATEGORY_ERROR = "DELETE_FOOD_CATEGORY_ERROR";
export const DELETE_FOOD_CATEGORY_SUCCESS = "DELETE_FOOD_CATEGORY_SUCCESS";
export const DELETE_FOOD_CATEGORY_INITIAL_STATE = "DELETE_FOOD_CATEGORY_INITIAL_STATE";



