export const FOOD_ITEM_INITIAL_STATE = "FOOD_ITEM_INITIAL_STATE";

export const CREATE_FOOD_ITEM = "CREATE_FOOD_ITEM";
export const CREATE_FOOD_ITEM_LOADING = "CREATE_FOOD_ITEM_LOADING";
export const CREATE_FOOD_ITEM_ERROR = "CREATE_FOOD_ITEM_ERROR";
export const CREATE_FOOD_ITEM_SUCCESS = "CREATE_FOOD_ITEM_SUCCESS";
export const CREATE_FOOD_ITEM_INITIAL_STATE = "CREATE_FOOD_ITEM_INITIAL_STATE";

export const LIST_FOOD_ITEM = "LIST_FOOD_ITEM";
export const LIST_FOOD_ITEM_LOADING = "LIST_FOOD_ITEM_LOADING";
export const LIST_FOOD_ITEM_ERROR = "LIST_FOOD_ITEM_ERROR";
export const LIST_FOOD_ITEM_SUCCESS = "LIST_FOOD_ITEM_SUCCESS";
export const LIST_FOOD_ITEM_INITIAL_STATE = "LIST_FOOD_ITEM_INITIAL_STATE";

export const GET_FOOD_ITEM = "GET_FOOD_ITEM";
export const GET_FOOD_ITEM_LOADING = "GET_FOOD_ITEM_LOADING";
export const GET_FOOD_ITEM_ERROR = "GET_FOOD_ITEM_ERROR";
export const GET_FOOD_ITEM_SUCCESS = "GET_FOOD_ITEM_SUCCESS";
export const GET_FOOD_ITEM_INITIAL_STATE = "GET_FOOD_ITEM_INITIAL_STATE";

export const EDIT_FOOD_ITEM_DATA = "EDIT_FOOD_ITEM_DATA";
export const EDIT_FOOD_ITEM = "EDIT_FOOD_ITEM";
export const EDIT_FOOD_ITEM_LOADING = "EDIT_FOOD_ITEM_LOADING";
export const EDIT_FOOD_ITEM_ERROR = "EDIT_FOOD_ITEM_ERROR";
export const EDIT_FOOD_ITEM_SUCCESS = "EDIT_FOOD_ITEM_SUCCESS";
export const EDIT_FOOD_ITEM_INITIAL_STATE = "EDIT_FOOD_ITEM_INITIAL_STATE";

export const DELETE_FOOD_ITEM_DATA = "DELETE_FOOD_ITEM_DATA";
export const DELETE_FOOD_ITEM = "DELETE_FOOD_ITEM";
export const DELETE_FOOD_ITEM_LOADING = "DELETE_FOOD_ITEM_LOADING";
export const DELETE_FOOD_ITEM_ERROR = "DELETE_FOOD_ITEM_ERROR";
export const DELETE_FOOD_ITEM_SUCCESS = "DELETE_FOOD_ITEM_SUCCESS";
export const DELETE_FOOD_ITEM_INITIAL_STATE = "DELETE_FOOD_ITEM_INITIAL_STATE";



