export const ORDER_ITEM_INITIAL_STATE = "ORDER_ITEM_INITIAL_STATE";

export const CREATE_ORDER_ITEM = "CREATE_ORDER_ITEM";
export const CREATE_ORDER_ITEM_LOADING = "CREATE_ORDER_ITEM_LOADING";
export const CREATE_ORDER_ITEM_ERROR = "CREATE_ORDER_ITEM_ERROR";
export const CREATE_ORDER_ITEM_SUCCESS = "CREATE_ORDER_ITEM_SUCCESS";
export const CREATE_ORDER_ITEM_INITIAL_STATE = "CREATE_ORDER_ITEM_INITIAL_STATE";

export const LIST_ORDER_ITEM = "LIST_ORDER_ITEM";
export const LIST_ORDER_ITEM_LOADING = "LIST_ORDER_ITEM_LOADING";
export const LIST_ORDER_ITEM_ERROR = "LIST_ORDER_ITEM_ERROR";
export const LIST_ORDER_ITEM_SUCCESS = "LIST_ORDER_ITEM_SUCCESS";
export const LIST_ORDER_ITEM_INITIAL_STATE = "LIST_ORDER_ITEM_INITIAL_STATE";

export const GET_ORDER_ITEM = "GET_ORDER_ITEM";
export const GET_ORDER_ITEM_LOADING = "GET_ORDER_ITEM_LOADING";
export const GET_ORDER_ITEM_ERROR = "GET_ORDER_ITEM_ERROR";
export const GET_ORDER_ITEM_SUCCESS = "GET_ORDER_ITEM_SUCCESS";
export const GET_ORDER_ITEM_INITIAL_STATE = "GET_ORDER_ITEM_INITIAL_STATE";

export const EDIT_ORDER_ITEM_DATA = "EDIT_ORDER_ITEM_DATA";
export const EDIT_ORDER_ITEM = "EDIT_ORDER_ITEM";
export const EDIT_ORDER_ITEM_LOADING = "EDIT_ORDER_ITEM_LOADING";
export const EDIT_ORDER_ITEM_ERROR = "EDIT_ORDER_ITEM_ERROR";
export const EDIT_ORDER_ITEM_SUCCESS = "EDIT_ORDER_ITEM_SUCCESS";
export const EDIT_ORDER_ITEM_INITIAL_STATE = "EDIT_ORDER_ITEM_INITIAL_STATE";

export const DELETE_ORDER_ITEM_DATA = "DELETE_ORDER_ITEM_DATA";
export const DELETE_ORDER_ITEM = "DELETE_ORDER_ITEM";
export const DELETE_ORDER_ITEM_LOADING = "DELETE_ORDER_ITEM_LOADING";
export const DELETE_ORDER_ITEM_ERROR = "DELETE_ORDER_ITEM_ERROR";
export const DELETE_ORDER_ITEM_SUCCESS = "DELETE_ORDER_ITEM_SUCCESS";
export const DELETE_ORDER_ITEM_INITIAL_STATE = "DELETE_ORDER_ITEM_INITIAL_STATE";



