export const PAYMENT_INITIAL_STATE = "PAYMENT_INITIAL_STATE";

export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const MAKE_PAYMENT_LOADING = "MAKE_PAYMENT_LOADING";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_ERROR = "MAKE_PAYMENT_ERROR";
export const MAKE_PAYMENT_INITIAL_STATE = "MAKE_PAYMENT_INITIAL_STATE";