export const SEARCH_INITIAL_STATE = "SEARCH_INITIAL_STATE";

export const SEARCH_RESULT = "SEARCH_RESULT";
export const SEARCH_RESULT_LOADING = "SEARCH_RESULT_LOADING";
export const SEARCH_RESULT_SUCCESS = "SEARCH_RESULT_SUCCESS";
export const SEARCH_RESULT_ERROR = "SEARCH_RESULT_ERROR";
export const SEARCH_RESULT_INITIAL_STATE = "SEARCH_RESULT_INITIAL_STATE";