export const USER_INITIAL_STATE = "USER_INITIAL_STATE";

export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_UP_USER_LOADING = "SIGN_UP_USER_LOADING";
export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const SIGN_UP_USER_ERROR = "SIGN_UP_USER_ERROR"
export const SIGN_UP_USER_INITIAL_STATE = "SIGN_UP_USER_INITIAL_STATE";

export const CONFIRM_EMAIL_USER ="CONFIRM_EMAIL_USER";
export const CONFIRM_EMAIL_USER_LOADING = "CONFIRM_EMAIL_USER_LOADING";
export const CONFIRM_EMAIL_USER_SUCCESS = "CONFIRM_EMAIL_USER_SUCCESS";
export const CONFIRM_EMAIL_USER_ERROR = "CONFIRM_EMAIL_USER_ERROR";
export const CONFIRM_EMAIL_USER_INITIAL_STATE = "CONFIRM_EMAIL_USER_INITIAL_STATE";

export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_USER_LOADING = "SIGN_IN_USER_LOADING";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_ERROR = "SIGN_IN_USER_ERROR"
export const SIGN_IN_USER_INITIAL_STATE = "SIGN_IN_USER_INITIAL_STATE";

export const GET_USER = "GET_USER";
export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR"
export const GET_USER_INITIAL_STATE = "GET_USER_INITIAL_STATE";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"
export const UPDATE_USER_INITIAL_STATE = "UPDATE_USER_INITIAL_STATE";

export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const SIGN_OUT_USER_LOADING = "SIGN_OUT_USER_LOADING";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";
export const SIGN_OUT_USER_ERROR = "SIGN_OUT_USER_ERROR"
export const SIGN_OUT_USER_INITIAL_STATE = "SIGN_OUT_USER_INITIAL_STATE";

export const RESET_PASSWORD_USER = "RESET_PASSWORD_USER";
export const RESET_PASSWORD_USER_LOADING = "RESET_PASSWORD_USER_LOADING";
export const RESET_PASSWORD_USER_SUCCESS = "RESET_PASSWORD_USER_SUCCESS";
export const RESET_PASSWORD_USER_ERROR = "RESET_PASSWORD_USER_ERROR";
export const RESET_PASSWORD_USER_INITIAL_STATE = "RESET_PASSWORD_USER_INITIAL_STATE";

export const CONFIRM_RESET_PASSWORD_USER = "CONFIRM_RESET_PASSWORD_USER";
export const CONFIRM_RESET_PASSWORD_USER_LOADING = "CONFIRM_RESET_PASSWORD_USER_LOADING";
export const CONFIRM_RESET_PASSWORD_USER_SUCCESS = "CONFIRM_RESET_PASSWORD_USER_SUCCESS";
export const CONFIRM_RESET_PASSWORD_USER_ERROR = "CONFIRM_RESET_PASSWORD_USER_ERROR";
export const CONFIRM_RESET_PASSWORD_USER_INITIAL_STATE = "CONFIRM_RESET_PASSWORD_USER_INITIAL_STATE";

export const UPDATE_USER_ADDRESS_DATA = "UPDATE_USER_ADDRESS_DATA";

export const UPDATE_USER_FULL_NAME_LOADING = "UPDATE_USER_FULL_NAME_LOADING";  
export const UPDATE_USER_FULL_NAME = "UPDATE_USER_FULL_NAME"
export const UPDATE_USER_FULL_NAME_SUCCESS = "UPDATE_USER_FULL_NAME_SUCCESS";
export const UPDATE_USER_FULL_NAME_ERROR = "UPDATE_USER_FULL_NAME_ERROR";
export const UPDATE_USER_FULL_NAME_INITIAL_STATE = "UPDATE_USER_FULL_NAME_INITIAL_STATE";