export const USER_ADDRESS_INITIAL_STATE = "USER_ADDRESS_INITIAL_STATE";

export const CREATE_USER_ADDRESS = "CREATE_USER_ADDRESS";
export const CREATE_USER_ADDRESS_LOADING = "CREATE_USER_ADDRESS_LOADING";
export const CREATE_USER_ADDRESS_ERROR = "CREATE_USER_ADDRESS_ERROR";
export const CREATE_USER_ADDRESS_SUCCESS = "CREATE_USER_ADDRESS_SUCCESS";
export const CREATE_USER_ADDRESS_INITIAL_STATE = "CREATE_USER_ADDRESS_INITIAL_STATE";


export const GET_USER_ADDRESS = "GET_USER_ADDRESS";
export const GET_USER_ADDRESS_LOADING = "GET_USER_ADDRESS_LOADING";
export const GET_USER_ADDRESS_ERROR = "GET_USER_ADDRESS_ERROR";
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS";
export const GET_USER_ADDRESS_INITIAL_STATE = "GET_USER_ADDRESS_INITIAL_STATE";

export const EDIT_USER_ADDRESS_DATA = "EDIT_USER_ADDRESS_DATA";
export const EDIT_USER_ADDRESS = "EDIT_USER_ADDRESS";
export const EDIT_USER_ADDRESS_LOADING = "EDIT_USER_ADDRESS_LOADING";
export const EDIT_USER_ADDRESS_ERROR = "EDIT_USER_ADDRESS_ERROR";
export const EDIT_USER_ADDRESS_SUCCESS = "EDIT_USER_ADDRESS_SUCCESS";
export const EDIT_USER_ADDRESS_INITIAL_STATE = "EDIT_USER_ADDRESS_INITIAL_STATE";

export const DELETE_USER_ADDRESS_DATA = "DELETE_USER_ADDRESS_DATA";
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";
export const DELETE_USER_ADDRESS_LOADING = "DELETE_USER_ADDRESS_LOADING";
export const DELETE_USER_ADDRESS_ERROR = "DELETE_USER_ADDRESS_ERROR";
export const DELETE_USER_ADDRESS_SUCCESS = "DELETE_USER_ADDRESS_SUCCESS";
export const DELETE_USER_ADDRESS_INITIAL_STATE = "DELETE_USER_ADDRESS_INITIAL_STATE";



